### ISSUE TITLE
Whitespace padding on <option> display values

### ISSUE THREAD

**Issue by grahampaulcook** [hmrc/play-ui#78]
The dropdown helper adds whitespace padding to the option display values. This is more noticeable when used in conjunction with the accessible-autocomplete component (https://github.com/alphagov/accessible-autocomplete)

Currently it looks like:-
![image](https://user-images.githubusercontent.com/11269301/30238391-bc5f4a46-953e-11e7-9e8d-87da8f25c0e7.png)

After the code change:-
![image](https://user-images.githubusercontent.com/11269301/30238404-f7d332ea-953e-11e7-9ee2-42cf6b948ee3.png)

I created a unit test which failed and then the dropdown helper was modified to remove the whitespace

[info] @helpers.dropDown
[info] - should render element options *** FAILED ***
[info]   "...ntry-AU" value="AU">[ Australia ]</option>" was not equal to "...ntry-AU" value="AU">[Australia]</option>" (DropDownSpec.scala:45)

The PR for this is https://github.com/hmrc/play-ui/pull/77

**Comment by rpowis** [comment]
Fixed in #77
